spring:
  # 导入敏感信息配置文件，'optional:'表示如果文件不存在也不会报错
  config:
    import: optional:file:./config/application-prod-secret.yml # 建议放在jar包外的config目录中

  # 开启分布式 Session
  session:
    store-type: redis

  # 数据库配置 (用户名和密码从 secret 文件读取)
  datasource:
    url: jdbc:mysql://prod-db-host:3306/research?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8

  # Redis 配置 (密码从 secret 文件读取)
  redis:
    host: prod-redis-host

  # ShardingSphere 数据源配置 (用户名和密码从 secret 文件读取)
  shardingsphere:
    datasource:
      research:
        jdbc-url: jdbc:mysql://prod-db-host:3306/research?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8

mybatis-plus:
  configuration:
    # 生产环境关闭 mybatis-plus 日志
    log-impl: ''

# 接口文档配置 (用户名和密码从 secret 文件读取)
knife4j:
  # 生产环境建议开启 basic 认证保护接口文档
  basic:
    enable: true
