# 生产环境配置文件 (application-prod.yml)

spring:
  # 不再使用文件导入！
  # config:
  #   import: optional:file:./config/application-prod-secret.yml

  # 开启分布式 Session
  session:
    store-type: redis

  # 数据库配置 (用户名和密码从环境变量读取)
  datasource:
    url: jdbc:mysql://prod-db-host:3306/research?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME} # 引用环境变量
    password: ${DB_PASSWORD} # 引用环境变量

  # Redis 配置 (密码从环境变量读取)
  redis:
    host: prod-redis-host

  # ShardingSphere 数据源配置 (用户名和密码从环境变量读取)
  shardingsphere:
    datasource:
      research:
        jdbc-url: jdbc:mysql://prod-db-host:3306/research?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: ${DB_USERNAME} # 引用环境变量
        password: ${DB_PASSWORD} # 引用环境变量

ai:
  apiKey: ${AI_API_KEY}
